language: python

python:
  - "3.5"

install:
  - pwd
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source=hdmi py.test -s

after_success:
  - coveralls

notifications:
  email: true
